name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:21-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/actions/wrapper-validation@v3
      - run: ./gradlew build publish --stacktrace --warning-mode fail
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
